apiVersion: v1
kind: Service
metadata:
  name: watch-api
  namespace: anime-bot
spec:
  type: ClusterIP
  selector:
    app: watch-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000

